// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_resampled_statistics
NumericVector compute_resampled_statistics(NumericVector a, NumericVector b, IntegerMatrix synthetic_treatment_idxs);
RcppExport SEXP _sceptre2_compute_resampled_statistics(SEXP aSEXP, SEXP bSEXP, SEXP synthetic_treatment_idxsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type synthetic_treatment_idxs(synthetic_treatment_idxsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_resampled_statistics(a, b, synthetic_treatment_idxs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sceptre2_compute_resampled_statistics", (DL_FUNC) &_sceptre2_compute_resampled_statistics, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sceptre2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
